policies:
  - type: commit
    spec:
      headerLength: 89
      dco: true
      gpg: true
      imperative: true
      conventional:
        types:
          - "feat"
            "fix"
            "chore"
            "BREAKING CHANGE"
        scopes:
          - "ci"
            "lint"
            "eslint"
            "ui"
            "pkg"
            "optimize"
