name: auditor
on: 
  push:
    branches:
    - master
    - develop
  pull_request:
    branches:
    - master
    - develop
  schedule:
    - cron: 0 16 * * 1 # run every monday at 16:00 UTC

jobs:
  audit:
    name: npm-audit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: audit
      run: npm audit
