name: auditor
on: 
  push:
    branches:
    - master
    - develop
  pull_request:
    branches:
    - master
    - develop
  schedule:
    - cron: '@daily'

jobs:
  audit:
    name: npm-audit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: npm-install
      run: npm i
    - name: audit
      run: npm audit
