name: linter
on: push
jobs:
  lint:
    name: eslint-js
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: npm-ci
      run: npm ci
    - name: lint-js
      run: npm run lint
