name: linter
on: push
jobs:
  lint:
    name: eslint-js
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: npm-install
      run: npm i
    - name: lint-js
      run: npm run lint
